# Format: filename=url
firehol-level4.list=https://iplists.firehol.org/files/firehol_level4.netset
spamhaus_drop.list=https://iplists.firehol.org/files/spamhaus_drop.netset
spamhaus_edrop.list=https://iplists.firehol.org/files/spamhaus_edrop.netset
iblocklist_ciarmy_malicious.list=https://iplists.firehol.org/files/iblocklist_ciarmy_malicious.netset
dm_tor.list=https://iplists.firehol.org/files/dm_tor.ipset
et_block.list=https://iplists.firehol.org/files/et_block.netset
blocklist_net_ua.list=https://iplists.firehol.org/files/blocklist_net_ua.ipset
firehol_webserver.list=https://iplists.firehol.org/files/firehol_webserver.netset
stopforumspam.list=https://iplists.firehol.org/files/stopforumspam.ipset
greensnow.list=https://iplists.firehol.org/files/greensnow.ipset
