name: Update Blacklists

on:
  schedule:
    - cron: '0 * * * *' # Hourly
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  update-blacklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/gen-blacklists.sh

      - name: Run script
        run: ./scripts/gen-blacklists.sh

      - name: Deploy to Release Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release
          publish_dir: ./output
          force_orphan: true
